### PR TITLE
fix dot in aws s3 bucketname

### LINKED ISSUE #25: panic: runtime error: index out of range [1] with length 1
```
juicesync file://dist s3://jfs-release/dist
panic: runtime error: index out of range [1] with length 1

goroutine 1 [running]:
github.com/juicedata/juicesync/object.newS3(0xc0000c1700, 0x13, 0x0, 0x0, 0x0, 0x0, 0x2, 0x2)
	/home/runner/work/juicesync/juicesync/object/s3.go:214 +0x86b
github.com/juicedata/juicesync/object.CreateStorage(0x7ffeefbfeafe, 0x2, 0xc0000c1700, 0x13, 0x0, 0x0, 0x0, 0x0, 0x1ce0260, 0xc0003079e0)
	/home/runner/work/juicesync/juicesync/object/object_storage.go:101 +0xac
main.createStorage(0x7ffeefbfeafe, 0x15, 0x1ce0260, 0xc0003079e0)
	/home/runner/work/juicesync/juicesync/main.go:100 +0x19d
main.main()
	/home/runner/work/juicesync/juicesync/main.go:133 +0x1ab
```

### PR DESCRIPTION
**Pull request by tonicbupt**
https://docs.aws.amazon.com/AmazonS3/latest/dev/UsingBucket.html
https://docs.amazonaws.cn/en_us/general/latest/gr/rande.html#cnnorthwest_region

the docs show that format will be `s3.REGION.amazonaws.com` or `s3-REGION.amazonaws.com`, so just use `".s3"` to split.

Closes #25 #26

### CODE REVIEW

File: object/s3.go [hunk 1]
```diff
@@ -208,33 +208,55 @@ func newS3(endpoint, accessKey, secretKey string) ObjectStorage {
...
 	}
 	if accessKey != "" {
 		awsConfig.Credentials = credentials.NewStaticCredentials(accessKey, secretKey, "")
 	}
 
+	var (
+		region string
+		bucket string
+	)
+	if !strings.Contains(uri.Host, ".s3") {
```
Comment (tonicbupt) [inline object/s3.go]: bucketname 可以有 `.`, 所以还是用这个来判断吧, 现在的托管式访问都有 `s3` 了

File: object/s3.go [hunk 2]
```diff
@@ -208,33 +208,55 @@ func newS3(endpoint, accessKey, secretKey string) ObjectStorage {
...
-	}
-	region := strings.Split(endpoint, ".")[0]
-	if region == "external-1" {
-		region = "us-east-1"
-	}
 
+	ssl := strings.ToLower(uri.Scheme) == "https"
 	awsConfig := &aws.Config{
-		Region:     &region,
+		Region:     aws.String("us-east-1"), // requires region...
```
Comment (tonicbupt) [inline object/s3.go]: 这个 region 必须指定一个, 之后拿到了再替换掉吧
